### ISSUE TITLE
Problem with user presence not properly updated in Gladys

### ISSUE THREAD

**Issue by kalon33** [GladysProject/gladys-bluetooth#2]
Using gladys-bluetooth to detect my bluetooth devices, I got some info sent to Gladys, but presence history is not working properly, and is always displaying the same thing "last seen xx min ago". When I left for the day, last detection timing increases, but I'm not noted as "left" (proper `USER_TIME_BEFORE_CONSIDERING_LEFT_HOME` variable is set to 15min in parameters). When device is detected, last detection time is always "26 minutes ago", never less.
![screenshot-2017-10-24 moi gladys](https://user-images.githubusercontent.com/460731/31964081-2c853ad2-b903-11e7-9356-9154e1ac6e85.png)

What's the problem? How can I fix it?

**Comment by Pierre-Gilles** [comment]
Have you created a script called regularly that call the function : 

```
gladys.house.checkUsersPresence();
```

( As I say in my tutorial here => https://gladysproject.com/fr/article/detecter-presence-porte-cle-bluetooth )

?

**Comment by kalon33** [comment]
Yep I did. I followed your tutorial, but at the end, in my timeline, I've "user last seen in house" events, but no "Left from House" or "Back to house" events generated. 

----- Mail original -----

De: "Pierre-Gilles" <notifications@github.com> 
À: "GladysProject/gladys-bluetooth" <gladys-bluetooth@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 24 Octobre 2017 22:29:11 
Objet: Re: [GladysProject/gladys-bluetooth] Problem with user presence not properly updated in Gladys (#2) 



Have you created a script called regularly that call the function : 
gladys.house.checkUsersPresence(); 


( As I say in my tutorial here => https://gladysproject.com/fr/article/detecter-presence-porte-cle-bluetooth ) 

?

**Comment by Pierre-Gilles** [comment]
What's your Gladys version?

**Comment by Pierre-Gilles** [comment]
For problems like that, please use Gladys forum =>

https://community.gladysproject.com

It's really hard for me to answer every message I receive, GitHub issues are more about reporting Gladys bugs/features requests. It will really help if you ask on the forum :) And we are way more on the forum ;)

**Comment by kalon33** [comment]
I use latest one.

My problem is that I followed your tutorial and still this is not working, so seems like a bug. And if it's a bug, github is the place to report them...
----- Mail d'origine -----
De: Pierre-Gilles <notifications@github.com>
À: GladysProject/gladys-bluetooth <gladys-bluetooth@noreply.github.com>
Cc: Nicolas Derive <kalon33@ubuntu.com>, Author <author@noreply.github.com>
Envoyé: Sat, 28 Oct 2017 11:26:56 +0200 (CEST)
Objet: Re: [GladysProject/gladys-bluetooth] Problem with user presence not properly updated in Gladys (#2)

What's your Gladys version?
