### ISSUE TITLE
Issue with package when install

### ISSUE THREAD

**Issue by RaymsDev** [GladysProject/gladys-bluetooth#4]
Hello,
J'ai installé galdys-bluetooth pour utiliser mon porte-clé NUT avec gladys mais j'ai des erreurs lors du 
npm install: 

pi@gladys:~/gladys-bluetooth $ npm install

> usb@1.2.0 install /home/pi/gladys-bluetooth/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/home/pi/.nvm/versions/node/v8.9.1/bin/node',
node-pre-gyp verb cli   '/home/pi/gladys-bluetooth/node_modules/usb/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.30
node-pre-gyp info using node@8.9.1 | linux | arm
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node" (not found)
node-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@8.9.1 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
make: Entering directory '/home/pi/gladys-bluetooth/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
libusb.target.mk:132: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/pi/gladys-bluetooth/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.64-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v8.9.1/bin/node" "/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/pi/gladys-bluetooth/node_modules/usb/src/binding"
gyp ERR! cwd /home/pi/gladys-bluetooth/node_modules/usb
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/pi/.nvm/versions/node/v8.9.1/bin/node /home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/gladys-bluetooth/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/gladys-bluetooth/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.64-v7+
node-pre-gyp ERR! command "/home/pi/.nvm/versions/node/v8.9.1/bin/node" "/home/pi/gladys-bluetooth/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/gladys-bluetooth/node_modules/usb
node-pre-gyp ERR! node -v v8.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute '/home/pi/.nvm/versions/node/v8.9.1/bin/node /home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/gladys-bluetooth/node_modules/usb/src/binding' (1)

> bluetooth-hci-socket@0.5.1 install /home/pi/gladys-bluetooth/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make: Entering directory '/home/pi/gladys-bluetooth/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emitErrnoError()’:
../src/BluetoothHciSocket.cpp:275:72: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /home/pi/.node-gyp/8.9.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/8.9.1/include/node/node.h:63,
                 from /home/pi/.node-gyp/8.9.1/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/pi/.node-gyp/8.9.1/include/node/v8.h:3832:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/pi/.node-gyp/8.9.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/pi/gladys-bluetooth/node_modules/bluetooth-hci-socket/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN gladys-bluetooth@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 217 packages in 58.252s

J'ai testé avec yarn mais sans succès:

`pi@gladys:~/gladys-bluetooth $ yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info xpc-connection@0.1.4: The platform "linux" is incompatible with this module.
info "xpc-connection@0.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠂ usb: gyp
[-/2] ⠂ waiting...
[-/2] ⠂ waiting...
[-/2] ⠂ waiting...
warning Error running install script for optional dependency: "/home/pi/gladys-bluetooth/node_modules/usb: Command failed.\nExit code: 1\nCommand: node-pre-gyp install --fallback-to-build\nArguments: \nDirectory: /home/pi/gladys-bluetooth/node_modules/usb\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.37\nnode-pre-gyp info using node@8.9.1 | linux | arm\nnode-pre-gyp info check checked for \"/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node\" (not found)\nnode-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz\nnode-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@8.9.1 (node-v57 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.1 | linux | arm\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.1 | linux | arm\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/pi/gladys-bluetooth/node_modules/usb/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/pi/.node-gyp/8.9.1/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/8.9.1',\ngyp info spawn args   '-Dnode_gyp_dir=/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/home/pi/.node-gyp/8.9.1/<(target_arch)/node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/home/pi/gladys-bluetooth/node_modules/usb',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\ngyp info ok \ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@8.9.1 | linux | arm\ngyp info spawn make\ngyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]\nmake: Entering directory '/home/pi/gladys-bluetooth/node_modules/usb/build'\n  CC(target) Release/obj.target/libusb/libusb/libusb/core.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/io.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o\n  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o\n../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory\n #include <libudev.h>\n                     ^\ncompilation terminated.\nlibusb.target.mk:132: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed\nmake: Leaving directory '/home/pi/gladys-bluetooth/node_modules/usb/build'\nmake: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1\ngyp ERR! build error \ngyp ERR! stack Error: `make` failed with exit code: 2\ngyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)\ngyp ERR! stack     at emitTwo (events.js:126:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:214:7)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)\ngyp ERR! System Linux 4.9.64-v7+\ngyp ERR! command \"/home/pi/.nvm/versions/node/v8.9.1/bin/node\" \"/home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node\" \"--module_name=usb_bindings\" \"--module_path=/home/pi/gladys-bluetooth/node_modules/usb/src/binding\"\ngyp ERR! cwd /home/pi/gladys-bluetooth/node_modules/usb\ngyp ERR! node -v v8.9.1\ngyp ERR! node-gyp -v v3.6.2\ngyp ERR! not ok \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute '/home/pi/.nvm/versions/node/v8.9.1/bin/node /home/pi/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/gladys-bluetooth/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/gladys-bluetooth/node_modules/usb/src/binding' (1)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/gladys-bluetooth/node_modules/node-pre-gyp/lib/util/compile.js:83:29)\nnode-pre-gyp ERR! stack     at emitTwo (events.js:126:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)\nnode-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)\nnode-pre-gyp ERR! System Linux 4.9.64-v7+\nnode-pre-gyp ERR! command \"/home/pi/.nvm/versions/node/v8.9.1/bin/node\" \"/home/pi/gladys-bluetooth/node_modules/usb/node_modules/.bin/node-pre-gyp\" \"instaDone in 34.01s.
`

**Comment by Pierre-Gilles** [comment]
Quelle est ta version de Node ? Tu installes ça sur l'image Raspbian Gladys fournie ?

**Comment by RaymsDev** [comment]
Je suis avec node v8.9.1, non j'ai installé gladys avec le git.

**Comment by Pierre-Gilles** [comment]
Ok, bizarre

Là comme ça avec juste ça dur de t'aider

Regarde peut être du côté du repo de Noble ( la lib Bluetooth qu'on utilise ici )  =>

https://github.com/sandeepmistry/noble

Pour d'autres questions de supports, passe plutôt par le forum Gladys => 

https://community.gladysproject.com 

Plein d'autres personnes de la communauté pourront t'aider :)
